# Generated by Django 4.2.7 on 2023-11-22 18:41

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('coin', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('blockchain', models.CharField(max_length=255)),
                ('transfer', models.FloatField()),
                ('swap', models.FloatField()),
                ('fiat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('blockchain', models.CharField(max_length=255)),
                ('icon', models.ImageField(help_text='icon Crypto', null=True, upload_to='media/icons')),
                ('swap', models.BooleanField(default=False, help_text='swap habilitado?')),
                ('bridge', models.BooleanField(default=False, help_text='bridge habilitado?')),
                ('limit_order', models.BooleanField(default=False, help_text='limit habilitado?')),
                ('time_transaction', models.IntegerField(blank=True, help_text='time in seconds', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='esta el usuario activo?')),
                ('tipo', models.CharField(choices=[('S', 'Super'), ('A', 'Admin'), ('U', 'Usuario'), ('B', 'Banco'), ('D', 'Defix')], default='U', help_text='Tipo de usuario', max_length=1, null=True)),
                ('usuario', models.OneToOneField(help_text='usuario asociado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tdataCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, help_text='Nombre del token', max_length=150, null=True)),
                ('wallet_defix', models.TextField(blank=True, help_text='ruta del token', max_length=150, null=True)),
                ('title', models.TextField(blank=True, help_text='titulo del token', max_length=150, null=True)),
                ('desc', models.TextField(blank=True, help_text='descripcion del token', max_length=150, null=True)),
                ('network', models.TextField(blank=True, help_text='descripcion de la red', max_length=150, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='tkycCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('R', 'Revision'), ('A', 'Aprobada'), ('C', 'Cancelada')], default='R', max_length=1)),
                ('observacion', models.TextField(blank=True, help_text='usuario con registros de kyc', max_length=240, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha de inicio de la transaccion', null=True)),
                ('fecha_final', models.DateTimeField(blank=True, help_text='Fecha de fin de la transaccion', null=True)),
                ('juridico', models.CharField(help_text='Natural o Juridico', max_length=1, null=True)),
                ('banco_cuenta', models.TextField(blank=True, help_text='detalle de informacion bancaria asociada al KYC', max_length=240, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='fecha de registro')),
                ('email', models.TextField(blank=True, help_text='email del usuario', max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Nombre Pais', max_length=120)),
                ('coin', models.TextField(blank=True, help_text='Mondeda del Pais', max_length=120, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to='media/paises')),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('kycventa', models.BooleanField(default=True, help_text='valida KYC en venta?')),
                ('kyccompra', models.BooleanField(default=True, help_text='valida KYC en compra?')),
                ('tasa', models.TextField(blank=True, help_text='tasa', max_length=120, null=True)),
                ('montoventa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto minimo para ventas FIAT', max_digits=14)),
                ('montocompra', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto minimo para compras FIAT', max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='tTipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, help_text='Nombre del Banco', max_length=120, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='tUserFiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='esta el token activo?')),
                ('referido', models.CharField(max_length=255)),
                ('tokenemail', models.CharField(max_length=255)),
                ('creacion', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='fecha de creacion de token')),
                ('usuario', models.OneToOneField(help_text='usuario asociado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tPaisServicioDefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Servicio Defix x Pais', max_length=120)),
                ('datos', models.TextField(blank=True, help_text='Detalle de infirmacion de FIAT x Pais', max_length=200, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('pais', models.ForeignKey(help_text='Pais asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
            ],
        ),
        migrations.CreateModel(
            name='tPaisDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Nombre Documento x Pais', max_length=120)),
                ('tipo', models.CharField(choices=[('I', 'Imagen'), ('A', 'Archivo'), ('T', 'Texto')], default='I', help_text='Tipo de documento', max_length=1, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('detalle', models.TextField(blank=True, help_text='Caracteristicas del documento', max_length=240, null=True)),
                ('opcional', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', help_text='Opcional Si o No', max_length=1, null=True)),
                ('juridico', models.CharField(choices=[('N', 'Natural'), ('J', 'Juridico')], default='N', help_text='Natural o Juridico', max_length=1, null=True)),
                ('pais', models.ForeignKey(help_text='Pais asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
            ],
        ),
        migrations.CreateModel(
            name='tPaisBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, help_text='Nombre del Banco', max_length=120, null=True)),
                ('codigo', models.TextField(blank=True, help_text='Codigo del Banco 4 digitos', max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Logo asociado al banco', null=True, upload_to='media/bancos')),
                ('tasa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa compra', max_digits=14)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto limite para validar para compras', max_digits=14)),
                ('montomin', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto minimo validar para compras', max_digits=14)),
                ('tasaaltomonto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa a aplicar con altos montos de compras', max_digits=14)),
                ('tasav', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa venta', max_digits=14)),
                ('montov', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto limite para validar para venta', max_digits=14)),
                ('montominv', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto minimo validar para venta', max_digits=14)),
                ('tasaaltomontov', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa a aplicar con altos montos de venta', max_digits=14)),
                ('comision', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='comision compra', max_digits=14)),
                ('comisionv', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='comision compra', max_digits=14)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('pais', models.ForeignKey(help_text='Pais asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=32)),
                ('contract', models.CharField(max_length=255)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('icon', models.ImageField(help_text='icon Crypto', null=True, upload_to='media/icons')),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='tkycDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('R', 'Revision'), ('A', 'Aprobada'), ('C', 'Cancelada')], default='R', max_length=1)),
                ('texto', models.TextField(blank=True, help_text='texto...', max_length=150, null=True)),
                ('documento', models.TextField(blank=True, help_text='documnto', max_length=150, null=True)),
                ('imagen', models.ImageField(help_text='Imagen KYC', null=True, upload_to='media/archivoskyc')),
                ('observacion', models.TextField(blank=True, help_text='usuario con registros de kyc', max_length=240, null=True)),
                ('tipo', models.CharField(help_text='Tipo de documento', max_length=1, null=True)),
                ('kyccabecera', models.ForeignKey(blank=True, help_text='Id de KYC asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tkyccabecera')),
                ('paisdocumento', models.ForeignKey(blank=True, help_text='Documento KFC pos Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tpaisdocumento')),
            ],
        ),
        migrations.CreateModel(
            name='tkycCuentaDefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.TextField(blank=True, help_text='Nombre del Titular', max_length=150, null=True)),
                ('cedula', models.TextField(blank=True, help_text='Numero de Identificacion', max_length=20, null=True)),
                ('telefono', models.TextField(blank=True, help_text='Numero de telefono del titular', max_length=50, null=True)),
                ('numerocuenta', models.TextField(blank=True, help_text='numero de cuenta del titular', max_length=20, null=True)),
                ('tipocuenta', models.TextField(blank=True, help_text='tipo  de cuenta del titular', max_length=20, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('banco', models.ForeignKey(blank=True, help_text='Id de Banco Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tpaisbanco')),
                ('pais', models.ForeignKey(help_text='Pais asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
                ('tipopago', models.ForeignKey(blank=True, help_text='Id de tipo de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ttipopago')),
            ],
        ),
        migrations.CreateModel(
            name='tkycCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.TextField(blank=True, help_text='Nombre del Titular', max_length=150, null=True)),
                ('cedula', models.TextField(blank=True, help_text='Numero de Identificacion', max_length=20, null=True)),
                ('telefono', models.TextField(blank=True, help_text='Numero de telefono', max_length=50, null=True)),
                ('numerocuenta', models.TextField(blank=True, help_text='numero de cuenta del titular', max_length=20, null=True)),
                ('tipocuenta', models.TextField(blank=True, help_text='tipo  de cuenta del titular', max_length=20, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('banco', models.ForeignKey(blank=True, help_text='Id de Banco Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tpaisbanco')),
                ('kyccabecera', models.ForeignKey(blank=True, help_text='Id de KYC asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tkyccabecera')),
                ('tipopago', models.ForeignKey(blank=True, help_text='Id de tipo de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ttipopago')),
            ],
        ),
        migrations.AddField(
            model_name='tkyccabecera',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Pais asociado', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tpais'),
        ),
        migrations.AddField(
            model_name='tkyccabecera',
            name='usuario',
            field=models.ForeignKey(help_text='usuario asociado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leer', models.BooleanField(default=False, help_text='Tiene opcion de leer?')),
                ('escribir', models.BooleanField(default=False, help_text='Tiene opcion de escribir?')),
                ('borrar', models.BooleanField(default=False, help_text='Tiene opcion de borrar?')),
                ('actualizar', models.BooleanField(default=False, help_text='Tiene opcion de actualizar?')),
                ('modulo', models.ForeignKey(help_text='Opcion de menu asociada', on_delete=django.db.models.deletion.CASCADE, to='backend.modulo')),
                ('perfil', models.ForeignKey(help_text='Usuario asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='FiatTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('1', 'Creado'), ('2', 'Asignado'), ('3', 'Procesado'), ('4', 'Completado'), ('5', 'Anulado')], default='1', max_length=1)),
                ('accion', models.CharField(choices=[('C', 'Compra'), ('V', 'Venta')], default='C', max_length=1)),
                ('referencia', models.TextField(blank=True, help_text='numero de referencia', max_length=20, null=True)),
                ('cripto', models.TextField(blank=True, help_text='nombre de la criptomoneda', max_length=20, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='cantidad de la criptomoneda', max_digits=14)),
                ('tasa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tasa de cambio', max_digits=14)),
                ('comision', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='comision', max_digits=14)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto', max_digits=14)),
                ('banco_nombre', models.TextField(blank=True, help_text='Nombre del Titular', max_length=150, null=True)),
                ('tipopago_nombre', models.TextField(blank=True, help_text='Nombre del Titular', max_length=150, null=True)),
                ('titular', models.TextField(blank=True, help_text='Nombre del Titular', max_length=150, null=True)),
                ('cedula', models.TextField(blank=True, help_text='Numero de Identificacion', max_length=20, null=True)),
                ('telefono', models.TextField(blank=True, help_text='Numero de telefono del titular', max_length=50, null=True)),
                ('numerocuenta', models.TextField(blank=True, help_text='numero de cuenta del titular', max_length=20, null=True)),
                ('tipocuenta', models.TextField(blank=True, help_text='tipo  de cuenta del titular', max_length=20, null=True)),
                ('fecha_creado', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='fecha de registro')),
                ('fecha_asignado', models.DateTimeField(blank=True, help_text='fecha de registro', null=True)),
                ('usuario_asignado', models.TextField(blank=True, help_text='usuario asignador', max_length=240, null=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, help_text='fecha de registro procesado', null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='fecha de registro completado', null=True)),
                ('fecha_anulado', models.DateTimeField(blank=True, help_text='fecha de registro aunulado', null=True)),
                ('observacion', models.TextField(blank=True, help_text='usuario', max_length=240, null=True)),
                ('adjuntofiat', models.ImageField(blank=True, help_text='adjunto soporte de la venta o compra', null=True, upload_to='media/fiat')),
                ('email', models.TextField(blank=True, help_text='email del usuario', max_length=240, null=True)),
                ('wallet', models.TextField(blank=True, help_text='wallet', max_length=240, null=True)),
                ('banco', models.ForeignKey(blank=True, help_text='Id de Banco Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tpaisbanco')),
                ('pais', models.ForeignKey(blank=True, help_text='Pais asociado', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
                ('tipopago', models.ForeignKey(blank=True, help_text='Id de tipo de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ttipopago')),
                ('usuario', models.ForeignKey(help_text='usuario asociado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
